In [1]:
import os
import torch

In [2]:
import sys
sys.path.append("../../")
print(sys.path)

['e:\\桌面\\research\\5-Demoire\\CVPR23-Unsupervised-Demoiring\\CUT\\models', 'e:\\anaconda\\python38.zip', 'e:\\anaconda\\DLLs', 'e:\\anaconda\\lib', 'e:\\anaconda', '', 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages', 'e:\\anaconda\\lib\\site-packages', 'e:\\anaconda\\lib\\site-packages\\win32', 'e:\\anaconda\\lib\\site-packages\\win32\\lib', 'e:\\anaconda\\lib\\site-packages\\Pythonwin', 'e:\\anaconda\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Administrator\\.ipython', '../../']


In [3]:
import mpe.models.mpe

In [4]:
mpe_model = mpe.models.mpe.MoirePatternExtractor()

In [6]:
x = torch.randn(1, 3, 256, 256)

output = mpe_model(x)

print(output[-1].shape)

torch.Size([1, 1, 256, 256])


In [8]:
x = torch.ones(1, 3, 5, 5)

y = torch.cat((output[-1], x), dim=1)

print(y.shape)


torch.Size([1, 4, 256, 256])


In [12]:
x = torch.randint(0, 255, (3, 5, 5))

x

tensor([[[241,  87,  20, 174, 142],
         [ 50, 197, 171,  30, 209],
         [ 88,  47, 188, 146,  99],
         [ 21, 226, 115,  61, 102],
         [246, 222,  67,  83,  83]],

        [[ 11, 194, 204, 203,   5],
         [220,  97, 154,   1, 204],
         [142, 233, 196, 104, 252],
         [ 14, 135, 112,  99, 212],
         [141,  56, 166,  53,  32]],

        [[100, 217,  15, 142, 144],
         [ 98,  24,  30,  43, 146],
         [141,  14,  52,  30, 131],
         [196, 118, 241, 188, 141],
         [198, 123,  21, 137, 127]]])

In [15]:
from torchvision.transforms import ToPILImage
import numpy as np
show = ToPILImage() # 可以把Tensor转成Image，方便可视化
show(x.astype(np.uint8)).show()

AttributeError: 'Tensor' object has no attribute 'astype'

In [43]:
x = torch.randn(2, 3, 5, 5)
print(x)
print(torch.sum(torch.abs(x)))

tensor([[[[-1.7164,  0.2209, -0.5220, -0.5235, -0.2165],
          [-0.4035,  1.1561,  0.4023,  1.3810,  2.1439],
          [-1.1463, -1.9165,  1.0400, -0.4716, -0.0455],
          [ 1.3412, -1.6083,  0.6483,  1.5215, -0.4276],
          [-0.9770, -1.2680,  1.1326,  0.0307, -0.6091]],

         [[ 0.9337, -0.4363, -0.2713,  0.3522,  0.4709],
          [-0.4542,  1.9955, -0.0365,  0.7978,  0.5330],
          [ 0.2796, -0.6294, -0.8248, -0.1620, -1.6498],
          [ 0.5295,  1.4607,  0.8027,  1.2168,  0.5164],
          [ 1.6423, -2.0708, -1.2309,  0.1753, -0.8248]],

         [[ 0.7959, -0.6109,  0.6438, -1.0378, -0.3830],
          [ 2.5225,  0.7214, -1.0091, -0.7975,  0.5101],
          [ 0.8515,  0.9048,  0.5969,  0.2549, -0.0861],
          [ 0.0301,  0.0036,  0.6028,  0.1016, -0.1868],
          [ 0.9195, -0.7050,  0.4674,  0.3071, -0.8257]]],


        [[[-0.1668,  0.2372, -0.5288, -0.2710,  0.1870],
          [ 0.8424,  0.0124, -0.7416,  1.2273,  0.7973],
          [ 2.0202,  0.

In [44]:
L1 = torch.norm(x, p=1, dim=(1, 2, 3))
L1

tensor([59.0433, 48.5293])

In [46]:
x = torch.randn(1, 3, 1, 1)
print(x)
print(x**3)

tensor([[[[2.3072]],

         [[0.4184]],

         [[0.3853]]]])
tensor([[[[12.2817]],

         [[ 0.0733]],

         [[ 0.0572]]]])


In [50]:
import cut_model

ImportError: attempted relative import with no known parent package

In [53]:
sys.path.append(".")
sys.path

['e:\\桌面\\research\\5-Demoire\\CVPR23-Unsupervised-Demoiring\\CUT\\models',
 'e:\\anaconda\\python38.zip',
 'e:\\anaconda\\DLLs',
 'e:\\anaconda\\lib',
 'e:\\anaconda',
 '',
 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages',
 'e:\\anaconda\\lib\\site-packages',
 'e:\\anaconda\\lib\\site-packages\\win32',
 'e:\\anaconda\\lib\\site-packages\\win32\\lib',
 'e:\\anaconda\\lib\\site-packages\\Pythonwin',
 'e:\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Administrator\\.ipython',
 '../../',
 '.',
 '.',
 '.']

In [55]:
import cut_model

ImportError: attempted relative import with no known parent package